### ISSUE TITLE
Como usuário web, quero acessar uma lista de eventos disponíveis no portal para acessar a página inicial de cada evento

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/events-calendar#1]

**Comment by wilsonmoura** [comment]
Tarefas relacionadas à funcionalidade:
- [ ] Gerar loop do custom post type `event` na homepage do site/subsite

**Comment by renatomurasaki** [comment]
Funcionalidades implementadas de acordo com a User Story e tarefas associadas.
