### ISSUE TITLE
Como usuário web, quero acessar o programa científico de um evento disponível no portal para acessar todas as sessões e apresentações disponíveis

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/events-calendar#2]

**Comment by wilsonmoura** [comment]
Tarefas relacionadas à funcionalidade:
- [ ] Gerar loop do custom post type `session`
- [ ] Gerar loop do custom post type `subsession` em cada sessão
- [ ] Gerar loop do custom post type `presentation` em cada sessão ou subsessão
- [ ] Gerar slider que exibe os horários das sessões de cada dia do programa

**Comment by renatomurasaki** [comment]
User story desenvolvida durante o [Sprint 1](https://github.com/bireme/events-calendar/issues?q=milestone%3A%22Sprint+-+Abril+1%22)
