### ISSUE TITLE
Como usuário web, quero acessar a página inicial de um evento a partir da lista de eventos disponíveis no portal

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/events-calendar#3]
Informações do evento:
1) Sobre
2) Apresentação
3) Programa
4) Notícia
5) Destaques

**Comment by wilsonmoura** [comment]
- [ ] Criação de template padrão, que listará os metadados na página do evento.
- [ ] O topo da página conterá links com âncoras para os campos dos metadados.
- [ ] O item **Programa** estará junto com os links com âncora no topo da página, porém remeterá para a página do programa.
- [ ] Se houver associação de um menu no evento, retirá-se do topo da página os links das âncoras para os campos dos metadados.
- [ ] Criar no metadado de **Evento** a opção de associar um menu do WP.

Nos casos de páginas de evento mais sofisticadas utilizando plugins do tipo Meta Slider, Ultimate Posts Widget, etc, se utilizara o plugin Page Builder, ficando a cargo de cada webmaster a criação da página.

**Comment by wilsonmoura** [comment]
Resolvido em edbf9f810021a0dbaa73319893cf26fb1d5d18bd

**Comment by renatomurasaki** [comment]
Funcionalidades implementadas de acordo com a User Story e tarefas associadas.
