### ISSUE TITLE
 Gerar loop do custom post type Event na homepage do site/subsite

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/events-calendar#8]
Tarefa ligada à issue #1

**Comment by renatomurasaki** [comment]
Modificações após reunião de revisão do Sprint - Abril 1:

- Aplicar o mesmo HTML do plug-in DirEve do WP
- Se o metadado do Evento relacionado à homepage não tiver preenchido, o link do Evento deve apontar para o template padrão que mostrará os metadados do Evento.

**Comment by wilsonmoura** [comment]
- [ ] Aplicar HTML do plug-in DirEve do WP na página de visualização da lista de eventos
- [ ] Criar template padrão que exibe os metadados do custom post type `event`

**Comment by wilsonmoura** [comment]
- [ ] Aplicar HTML do plug-in DirEve do WP na página de visualização da lista de eventos
- [ ] Criar template padrão que exibe os metadados do custom post type `event`

**Comment by wilsonmoura** [comment]
Resolvido em dafe0349c3b4add845c6b81e83471fe1956690e9 e edbf9f810021a0dbaa73319893cf26fb1d5d18bd
